const $ = s => document.querySelector(s);
const fmt = (n, d = 2) => Number.isFinite(n) ? Number(n).toFixed(d) : '暂无';
const money = n => Number.isFinite(n) ? (Math.abs(n)>=1e8?(n/1e8).toFixed(2)+'亿元':Math.round(n).toLocaleString()+'元') : '暂无';
const clamp = (n,min=0,max=100) => Math.max(min,Math.min(max,n));
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const aiText = value => esc(value).replace(/^\s*#{1,6}\s*/gm,'').replace(/\*\*(.*?)\*\*/g,'$1').replace(/^\s*[-*]\s+/gm,'• ');
let currentUser = null;
const store = {
  get(k, fallback) { try { return JSON.parse(localStorage.getItem(`allen_${currentUser?.username||'guest'}_${k}`)) ?? fallback; } catch { return fallback; } },
  set(k, v) { localStorage.setItem(`allen_${currentUser?.username||'guest'}_${k}`, JSON.stringify(v));if(['watch','portfolio','theses'].includes(k))scheduleCloudSave() }
};
const seedWatch = [
  {symbol:'601138.SS',code:'601138',name:'工业富联'},
  {symbol:'000977.SZ',code:'000977',name:'浪潮信息'},
  {symbol:'688981.SS',code:'688981',name:'中芯国际'},
  {symbol:'300750.SZ',code:'300750',name:'宁德时代'},
  {symbol:'0700.HK',code:'00700',name:'腾讯控股'}
];
const state = {
  page:'dashboard', stock:null, tab:'conclusion', loading:false,
  watch:store.get('watch', seedWatch),
  portfolio:store.get('portfolio', [{symbol:'601138.SS',name:'工业富联',buy:58.4,qty:1000,date:'2026-07-20',thesis:'AI服务器需求增长，公司利润持续改善。'}]),
  theses:store.get('theses', [{symbol:'601138.SS',name:'工业富联',created:'2026-07-20',cycle:'中长期',reason:'看好 AI 算力行业和服务器需求，预期公司利润增长。',risk:'AI资本开支下降或主要客户订单恶化。'}]),
  aiMessages:store.get('aiMessages',[]), aiScreen:null, prediction:null, predictionHistory:[],
  aiScreenCriteria:{horizon:'中期',risk:'中',capital:''}
};
const nav = [
  ['dashboard','⌂','首页'],['watchlist','★','我的股票池'],['search','⌕','股票搜索'],['aiChat','✦','AI 研究对话'],['aiScreen','◈','AI 智能选股'],['prediction','⌁','趋势预测中心'],['decisions','◎','AI 买卖决策'],
  ['risks','△','风险预警中心'],['events','□','未来事件中心'],['portfolio','▣','我的持仓'],['theses','✎','我的投资逻辑'],['brief','☀','每日 AI 简报'],['settings','⚙','系统设置']
];
const adminNav=['admin','♙','用户管理'];
const pageMeta = Object.fromEntries([...nav,adminNav].map(x => [x[0],x[2]]));
function loadUserState(){state.watch=store.get('watch',seedWatch);state.portfolio=store.get('portfolio',[]);state.theses=store.get('theses',[]);state.aiMessages=store.get('aiMessages',[]);state.aiScreenCriteria=store.get('aiScreenCriteria',{horizon:'中期',risk:'中',capital:''})}
let cloudSaveTimer=null;
function scheduleCloudSave(){if(!currentUser)return;clearTimeout(cloudSaveTimer);cloudSaveTimer=setTimeout(()=>api('/api/user-state',{method:'PUT',body:JSON.stringify({watch:state.watch,portfolio:state.portfolio,theses:state.theses})}).catch(()=>{}),700)}
async function loadCloudState(){const result=await api('/api/user-state');if(result.state){state.watch=result.state.watch||[];state.portfolio=result.state.portfolio||[];state.theses=result.state.theses||[]}else await api('/api/user-state',{method:'PUT',body:JSON.stringify({watch:state.watch,portfolio:state.portfolio,theses:state.theses})})}

async function api(url, options={}) {
  const res = await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});
  const data = await res.json().catch(()=>({}));
  if (!res.ok) throw new Error(data.error || '请求失败');
  return data;
}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function badge(score){return score>=80?['green','重点关注']:score>=60?['yellow','等待更好机会']:score>=40?['orange','谨慎观察']:['red','风险较高']}
function navRender(){ const items=currentUser?.role==='admin'?[...nav.slice(0,-1),adminNav,nav.at(-1)]:nav;$('#nav').innerHTML=items.map(([id,icon,name])=>`<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span>${name}</button>`).join(''); }
function go(page){state.page=page;navRender();$('#breadcrumb').textContent=page==='dashboard'?'OVERVIEW':'ALLEN STOCK / '+page.toUpperCase();$('#pageTitle').textContent=pageMeta[page]||'股票详情';$('.sidebar').classList.remove('open');render()}

async function quote(symbol){return api('/api/stock/'+encodeURIComponent(symbol))}
async function quoteMany(items){return Promise.all(items.map(async x=>{try{return {...x,...await quote(x.symbol)}}catch{return {...x,unavailable:true}}}))}
function stockTable(rows, withRemove=false){return `<div class="table-wrap"><table class="table"><thead><tr><th>股票</th><th>当前价格</th><th>今日涨跌</th><th>AI评分</th><th>当前状态</th><th>风险</th><th>操作</th></tr></thead><tbody>${rows.map(x=>{const [c,t]=badge(x.technical?.score??60);const ch=x.changePct;return `<tr><td><div class="stock-title">${x.name}</div><div class="stock-code">${x.code||x.symbol}</div></td><td>${x.unavailable?'暂无':fmt(x.price)} ${x.currency||''}</td><td class="${ch>=0?'up':'down'}">${Number.isFinite(ch)?(ch>=0?'+':'')+fmt(ch)+'%':'暂无'}</td><td><b>${x.technical?.score??'—'}</b></td><td><span class="badge ${c}">${t}</span></td><td><span class="badge ${x.technical?.score<50?'red':'yellow'}">${x.technical?.score<50?'高':'中'}</span></td><td><button class="link" data-stock="${x.symbol}" data-name="${x.name}">分析</button>${withRemove?` · <button class="link" data-remove="${x.symbol}">移除</button>`:''}</td></tr>`}).join('')}</tbody></table></div>`}
function loading(){return '<div class="card empty">正在读取真实行情…</div>'}

async function dashboard(){
  $('#content').innerHTML=loading(); const rows=await quoteMany(state.watch.slice(0,5));
  const risks=rows.filter(x=>(x.technical?.score??60)<50).length, positives=rows.filter(x=>(x.changePct??0)>1).length;
  $('#content').innerHTML=`<div class="grid g4">
    <div class="card"><div class="muted">股票池</div><div class="metric">${state.watch.length}</div><span class="badge blue">私人关注</span></div>
    <div class="card"><div class="muted">积极变化</div><div class="metric">${positives}</div><span class="badge green">今日上涨 &gt; 1%</span></div>
    <div class="card"><div class="muted">需要关注</div><div class="metric">${Math.max(0,rows.length-positives-risks)}</div><span class="badge yellow">等待条件</span></div>
    <div class="card"><div class="muted">重要风险</div><div class="metric">${risks}</div><span class="badge red">评分低于 50</span></div></div>
    <section class="section grid g2"><div class="card"><h2>🧠 今日 AI 总结</h2><p>系统已对股票池的最新价格、均线和动量进行检查。</p><p class="note">${positives?'有 '+positives+' 只股票出现积极价格变化，但仍需结合基本面与风险判断。':'今日暂未发现明显的积极价格变化，继续等待条件改善。'}</p></div><div class="card"><h2>🚨 今日最重要事件</h2>${rows.sort((a,b)=>Math.abs(b.changePct||0)-Math.abs(a.changePct||0)).slice(0,2).map(x=>`<div class="event"><div class="event-icon">${(x.changePct||0)>=0?'↗':'↘'}</div><div><b>${x.name}</b><p class="muted">今日波动 ${(x.changePct||0)>=0?'+':''}${fmt(x.changePct)}%，建议查看完整分析。</p><button class="link" data-stock="${x.symbol}" data-name="${x.name}">查看详情 →</button></div></div>`).join('')}</div></section>
    <section class="section"><div class="section-head"><h2>快捷入口</h2></div><div class="grid g4">${[['watchlist','★','我的股票池'],['search','⌕','搜索股票'],['decisions','◎','AI 分析'],['risks','△','风险中心']].map(x=>`<div class="card quick" data-go="${x[0]}"><div class="big-icon">${x[1]}</div><b>${x[2]}</b><p class="muted">打开 →</p></div>`).join('')}</div></section>
    <section class="section"><div class="section-head"><h2>我的股票池</h2><button class="link" data-go="watchlist">查看全部 →</button></div><div class="card">${stockTable(rows)}</div></section>${disclaimer()}`;
}
async function watchlist(){ $('#content').innerHTML=loading();const rows=await quoteMany(state.watch);$('#content').innerHTML=`<div class="section-head"><div><h2>我的股票池</h2><p class="muted">追踪真实行情与综合条件</p></div><button class="primary" data-go="search">＋ 添加股票</button></div><div class="card">${stockTable(rows,true)}</div>${disclaimer()}` }
function searchPage(){ $('#content').innerHTML=`<div class="card"><h2>搜索股票</h2><p class="muted">支持股票名称、A股代码、港股代码和美股代码</p><form id="searchForm" class="searchbox"><input id="searchInput" class="input" placeholder="例如：工业富联、601138、AAPL"><button class="primary">搜索</button></form></div><div id="searchResults" class="section"></div>${disclaimer()}` }
async function doSearch(q){const box=$('#searchResults');box.innerHTML=loading();try{const data=await api('/api/search?q='+encodeURIComponent(q));box.innerHTML=`<div class="card"><h2>搜索结果</h2>${data.quotes.length?`<div class="table-wrap"><table class="table"><thead><tr><th>名称</th><th>代码</th><th>市场</th><th>操作</th></tr></thead><tbody>${data.quotes.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.symbol}</td><td>${x.exchange}</td><td><button class="secondary" data-add="${x.symbol}" data-name="${x.name}">加入股票池</button> <button class="link" data-stock="${x.symbol}" data-name="${x.name}">立即分析</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">没有找到匹配股票</div>'}</div>`}catch(e){box.innerHTML=`<div class="card empty">${e.message}</div>`}}

function aiMessagesHtml(){return state.aiMessages.length?state.aiMessages.map(item=>`<div class="chat-message ${item.role}"><div class="chat-role">${item.role==='user'?'我':'Allen AI'}</div><div class="chat-text">${aiText(item.content)}</div></div>`).join(''):'<div class="empty">输入股票代码和问题，AI 会先读取真实行情再回答。</div>'}
async function aiChatPage(){let status={configured:false,provider:'AI'};try{status=await api('/api/ai/status')}catch{}$('#content').innerHTML=`<div class="section-head"><div><h2>✦ AI 股票研究对话</h2><p class="muted">结合真实行情连续提问 · ${status.configured?status.provider+' 已连接':'AI 接口待管理员配置'}</p></div><button class="ghost" data-clear-chat>清空对话</button></div><div class="ai-layout"><div class="card chat-panel"><div id="chatMessages" class="chat-messages">${aiMessagesHtml()}</div><form id="aiChatForm" class="chat-form"><input class="input" name="symbol" maxlength="12" placeholder="股票代码，例如 601138"><textarea name="question" required maxlength="1200" placeholder="例如：工业富联当前有哪些机会和风险？"></textarea><button class="primary" type="submit">发送给 AI</button></form></div><div class="card"><h2>可以这样问</h2>${['现在处于什么趋势？','当前最大的风险是什么？','什么条件满足后更值得关注？','短期和中期判断有什么不同？'].map(q=>`<button class="suggestion" data-ai-question="${q}">${q}</button>`).join('')}<p class="note section">AI 只能使用已核验行情，不会读取你的国信证券账户，也不会替你下单。</p></div></div>${disclaimer()}`;setTimeout(()=>{const box=$('#chatMessages');if(box)box.scrollTop=box.scrollHeight},0)}

async function aiScreenPage(){let status={configured:false,provider:'AI'};try{status=await api('/api/ai/status')}catch{}const result=state.aiScreen,c=state.aiScreenCriteria||{horizon:'中期',risk:'中',capital:''};const opts=(values,current)=>values.map(v=>`<option ${v===current?'selected':''}>${v}</option>`).join('');$('#content').innerHTML=`<div class="card"><div class="section-head"><div><h2>◈ AI 智能选股</h2><p class="muted">沪深 A 股活跃股票扩大样本 · ${status.configured?status.provider+' 已连接':'AI 接口待管理员配置'}</p></div><span class="badge blue">研究辅助</span></div><form id="aiScreenForm" class="screen-form"><label>投资周期<select class="input" name="horizon">${opts(['短期','中期','长期'],c.horizon)}</select></label><label>风险偏好<select class="input" name="risk">${opts(['低','中','高'],c.risk)}</select></label><label>参考资金（元）<input class="input" name="capital" type="number" min="0" step="1000" value="${esc(c.capital)}" placeholder="例如 60000"></label><button class="primary" type="submit">开始筛选</button></form><p class="footer-note">从约 1200 只成交较活跃的沪深 A 股中筛选，并排除 ST、退市整理、低流动性和无法核验行情的股票。周期与风险偏好会真实影响排序。</p></div><div id="screenResult" class="section">${result?`<div class="card ai-report"><div class="section-head"><h2>AI 候选研究报告</h2><span class="badge green">核验 ${result.sampleSize} 只 / 市场约 ${result.marketTotal||'—'} 只</span></div><p class="muted">本次条件：${result.horizon} · ${result.risk}风险${result.capital?' · 参考资金 '+Number(result.capital).toLocaleString()+'元':''}</p><div class="chat-text">${aiText(result.answer)}</div></div>`:'<div class="card empty">选择周期和风险偏好后开始筛选</div>'}</div>${disclaimer()}`}

async function openStock(symbol,name){state.page='stock';state.tab='conclusion';state.stock={symbol,name};navRender();$('#pageTitle').textContent='股票详情';$('#breadcrumb').textContent='RESEARCH / '+symbol;$('#content').innerHTML=loading();try{const [market,research]=await Promise.allSettled([quote(symbol),api('/api/research/'+encodeURIComponent(symbol))]);if(market.status!=='fulfilled')throw market.reason;state.stock={...state.stock,...market.value,research:research.status==='fulfilled'?research.value:null};renderStock()}catch(e){$('#content').innerHTML=`<div class="card empty"><h2>行情暂不可用</h2><p>${e.message}</p><button class="secondary" data-go="search">返回搜索</button></div>`}}
function spark(history=[]){if(history.length<2)return'';const vals=history.map(x=>x.close),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;const pts=vals.map((v,i)=>`${(i/(vals.length-1))*100},${100-((v-min)/span)*90}`).join(' ');return `<svg class="spark" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="${pts}"/></svg>`}
function renderStock(){const s=state.stock,t=s.technical,[c,label]=badge(t.score),trend=t.ma5>t.ma20?'上升':'震荡/走弱';$('#content').innerHTML=`<div class="card hero"><div class="hero-row"><div><p class="eyebrow">${s.exchange} · ${s.symbol}</p><h2>${s.research?.name||s.name}</h2><div class="price">${fmt(s.price)} <small>${s.currency}</small></div><span class="${s.changePct>=0?'up':'down'}">${s.changePct>=0?'+':''}${fmt(s.changePct)}%</span><p class="muted">真实行情 · 可能存在延迟</p></div><div><span class="badge ${c}">${label}</span><div class="score-ring" style="--score:${t.score}%"><b>${t.score}</b></div></div></div>${spark(s.history)}</div>
  <div class="tabs">${[['conclusion','AI 综合结论'],['company','公司研究'],['finance','财务分析'],['industry','行业分析'],['news','新闻与公告'],['events','未来事件'],['risks','风险雷达'],['technical','技术分析'],['trade','买卖决策']].map(x=>`<button class="tab ${state.tab===x[0]?'active':''}" data-tab="${x[0]}">${x[1]}</button>`).join('')}</div><div id="stockModule"></div>${sourceQuality(s.research)}${disclaimer()}`;renderStockModule()}
function sourceQuality(research){return `<div class="card section"><div class="section-head"><h2>数据来源与质量</h2><span class="badge ${research?'green':'yellow'}">${research?'已核验':'部分数据暂不可用'}</span></div><div class="source-grid">${research?.sources?.map(source=>`<div class="source-item"><span class="status-dot ${source.ok?'':'bad'}"></span><div><b>${esc(source.name)}</b><p>${source.ok?'字段完整度 '+source.completeness+'%':'连接失败'}${source.updatedAt?' · 更新 '+String(source.updatedAt).slice(0,10):''}</p></div></div>`).join('')||'<p class="muted">公司、财务或公告数据源暂时没有返回结果；价格行情仍可独立使用。</p>'}</div></div>`}
function renderStockModule(){const s=state.stock,t=s.technical,[c,label]=badge(t.score),r=s.research||{},p=r.company,f=r.finance,anns=r.announcements||[];let html='';
 const tone=value=>!Number.isFinite(value)?'yellow':value>=15?'green':value>=0?'blue':value>-15?'orange':'red';
 const financeCard=(title,value,detail,color='blue')=>`<div class="card"><span class="badge ${color}">${f?.reportName||'数据不足'}</span><h2 class="section">${title}</h2><div class="metric small">${value}</div><p class="muted">${detail}</p></div>`;
 if(state.tab==='conclusion')html=`<div class="grid g2"><div class="card"><h2>🧠 当前最重要的三件事</h2><div class="insight"><span class="insight-num">1</span><div><b>经营变化</b><p>${f?`最近报告期营收同比${signed(f.revenueGrowth)}，归母净利润同比${signed(f.profitGrowth)}。`:'财务数据源本次未返回结果，需要稍后重新核验。'}</p></div></div><div class="insight"><span class="insight-num">2</span><div><b>价格风险</b><p>${s.price>t.high20*.97?'当前价格接近最近20日高位，短期追高风险较高。':t.ma5>t.ma20?'最近5日平均价格高于20日平均价格，短期趋势相对改善。':'短期趋势仍偏弱，需要等待价格确认。'}</p></div></div><div class="insight"><span class="insight-num">3</span><div><b>当前策略</b><p>${label}。综合财务、公告和趋势条件判断，不因单日涨跌行动。</p></div></div></div>${periodCards()}</div>`;
 if(state.tab==='company')html=p?`<div class="grid g2"><div class="card"><h2>${esc(p.fullName||r.name)}</h2><p class="note">${esc(p.introduction||'暂无公司简介')}</p><h3 class="section">主要业务范围</h3><p>${esc(p.business||'公开资料暂未返回详细经营范围')}</p></div><div class="card"><h2>公司资料</h2>${[['所属行业',p.industry],['监管行业',p.regulatoryIndustry],['上市交易所',p.exchange],['董事长/负责人',p.chairman],['总经理',p.generalManager],['所在地区',p.location],['公司网站',p.website]].map(([k,v])=>`<div class="factor-row"><span>${k}</span><b>${esc(v||'暂无')}</b></div>`).join('')}</div></div>`:'<div class="card empty">公司资料源暂时不可用，请稍后重试。</div>';
 if(state.tab==='finance')html=f?`<div class="grid g3">${financeCard('营业收入',money(f.revenue),`同比 ${signed(f.revenueGrowth)}`,tone(f.revenueGrowth))}${financeCard('归母净利润',money(f.netProfit),`同比 ${signed(f.profitGrowth)}`,tone(f.profitGrowth))}${financeCard('利润质量',`${fmt(f.grossMargin,1)}% 毛利率`,`净利率 ${fmt(f.netMargin,1)}%`,tone(f.netMargin))}${financeCard('现金流安全',`${fmt(f.operatingCashRevenue,1)}%`,`经营现金流占营业收入`,tone(f.operatingCashRevenue))}${financeCard('负债风险',`${fmt(f.debtRatio,1)}%`,`资产负债率 · 流动比率 ${fmt(f.currentRatio,2)}`,f.debtRatio>70?'red':f.debtRatio>55?'orange':'green')}${financeCard('应收与存货',`${fmt(f.receivableDays,1)}天`,`应收账款周转天数 · 存货周转 ${fmt(f.inventoryDays,1)}天`,'blue')}</div><div class="card section"><div class="section-head"><h2>历史报告趋势</h2><span class="badge blue">${esc(f.reportName)}</span></div><div class="table-wrap"><table class="table"><thead><tr><th>报告期</th><th>营业收入</th><th>营收增长</th><th>归母净利润</th><th>利润增长</th><th>毛利率</th><th>净资产收益率</th></tr></thead><tbody>${f.history.map(row=>`<tr><td>${esc(row.reportName)}</td><td>${money(row.revenue)}</td><td class="${row.revenueGrowth>=0?'up':'down'}">${signed(row.revenueGrowth)}</td><td>${money(row.netProfit)}</td><td class="${row.profitGrowth>=0?'up':'down'}">${signed(row.profitGrowth)}</td><td>${fmt(row.grossMargin,1)}%</td><td>${fmt(row.roe,1)}%</td></tr>`).join('')}</tbody></table></div></div>`:'<div class="card empty"><h2>财务数据本次未返回</h2><p>系统不会使用价格数据代替财务报表，请稍后重新打开。</p></div>';
 if(state.tab==='industry')html=`<div class="grid g2"><div class="card"><h2>行业归属</h2><div class="metric small">${esc(p?.industry||'暂未识别')}</div><p>${esc(p?.regulatoryIndustry||'')}</p><div class="condition">✓ <span>趋势预测已与上证综合指数比较</span></div><div class="condition">${p?.industry?'✓':'○'} <span>公司行业分类来自公开公司资料</span></div><div class="condition">○ <span>行业指数历史对照仍需稳定的板块代码映射</span></div></div><div class="card"><h2>经营与行业线索</h2><p class="note">${esc(p?.introduction||'暂无可核验行业资料')}</p><p>这里不会用固定分数假装行业前景。行业需求、竞争和政策结论需要结合公告、财务变化及可靠行业资料持续更新。</p></div></div>`;
 if(state.tab==='news')html=`<div class="grid g2"><div class="card"><div class="section-head"><h2>公司公告</h2><span class="badge green">可核验</span></div>${anns.length?anns.slice(0,8).map(a=>`<div class="event"><div class="event-icon">告</div><div><b>${esc(a.title)}</b><p class="muted">${esc(a.date)} · ${esc(a.category)}</p><a class="link" href="${a.link}" target="_blank" rel="noopener">查看公告 →</a></div></div>`).join(''):'<div class="empty">公告源暂时无数据</div>'}</div><div class="card"><div class="section-head"><h2>新闻线索</h2><span class="badge blue">需核验</span></div>${s.news?.length?s.news.slice(0,8).map(n=>`<div class="event"><div class="event-icon">闻</div><div><b>${esc(n.title)}</b><p class="muted">${esc(n.publisher||'来源未知')} · ${n.published?new Date(n.published*1000).toLocaleDateString('zh-CN'):''}</p>${n.link?`<a class="link" href="${n.link}" target="_blank" rel="noopener">查看原文 →</a>`:''}</div></div>`).join(''):'<div class="empty">暂无新闻线索</div>'}</div></div>`;
 if(state.tab==='events')html=`<div class="grid g2"><div class="card"><h2>近期重要公告事件</h2>${anns.slice(0,6).map(a=>`<div class="event"><div class="event-icon">◉</div><div><b>${esc(a.category)}</b><p>${esc(a.title)}</p><p class="muted">${esc(a.date)}</p></div></div>`).join('')||'<div class="empty">暂无公告事件</div>'}</div><div class="card"><h2>下一步需要追踪</h2>${['下一份定期财务报告','股东大会及业绩说明会','回购、增减持和重大合同','监管政策与行业需求变化'].map(x=>`<div class="condition">□ <span>${x}</span></div>`).join('')}<p class="note section">只有公告明确日期时才显示确定日期；没有可靠日期的事件不会由 AI 猜测。</p></div></div>`;
 if(state.tab==='risks'){const cashRisk=Number.isFinite(f?.operatingCashRevenue)?clamp(70-f.operatingCashRevenue*3):50,debtRisk=Number.isFinite(f?.debtRatio)?clamp((f.debtRatio-35)*2+35):50,profitRisk=Number.isFinite(f?.profitGrowth)?clamp(50-f.profitGrowth):50;html=`<div class="grid g2"><div class="card"><h2>风险雷达</h2>${[['利润增长风险',profitRisk],['现金流风险',cashRisk],['负债风险',debtRisk],['应收账款风险',Number.isFinite(f?.receivableRevenue)?clamp(f.receivableRevenue*4):50],['近期高位风险',s.price>t.high20*.95?82:45],['短期波动风险',Math.min(90,Math.abs(s.changePct||0)*10+45)]].map(x=>bar(x[0],Math.round(x[1]),x[1]>70?'#d64545':x[1]>55?'#d99a18':'#0f9d68')).join('')}</div><div class="card"><h2>风险依据</h2><p class="note">最近报告期：营收同比 ${signed(f?.revenueGrowth)}，利润同比 ${signed(f?.profitGrowth)}，资产负债率 ${fmt(f?.debtRatio,1)}%，经营现金流占营收 ${fmt(f?.operatingCashRevenue,1)}%。</p><p>行情区间：当前价 ${fmt(s.price)}，最近20日低位 ${fmt(t.low20)}，高位 ${fmt(t.high20)}。</p><p class="warning">财务风险分用于提示需要检查的方向，不代表信用评级或确定损失。</p></div></div>`}
 if(state.tab==='technical')html=`<div class="grid g3"><div class="card"><div class="muted">短期趋势</div><div class="metric small">${t.ma5>t.ma20?'🟢 上升':'🟡 震荡/偏弱'}</div><p>最近5日平均价格 ${fmt(t.ma5)}</p></div><div class="card"><div class="muted">中期趋势</div><div class="metric small">${t.ma20>t.ma60?'🟢 上升':'🟠 偏弱'}</div><p>最近20日平均价格 ${fmt(t.ma20)}</p><p>最近60日平均价格 ${fmt(t.ma60)}</p></div><div class="card"><div class="muted">关键价格区间</div><div class="metric small">${fmt(t.low20)}—${fmt(t.high20)}</div><p>最近20个交易日</p></div></div><div class="card section"><h2>最近90日价格走势</h2>${spark(s.history)}</div>`;
 if(state.tab==='trade')html=`<div class="grid g3"><div class="card"><span class="badge green">📥 入场</span><h2 class="section">条件式判断</h2>${conditions(['价格调整结束','最近5日平均价格重新高于20日平均价格','成交量恢复','营收和利润未明显恶化'],[s.price<t.ma20,t.ma5>t.ma20,Boolean(t.volume),Number.isFinite(f?.profitGrowth)&&f.profitGrowth>=0])}</div><div class="card"><span class="badge yellow">⏳ 等待</span><h2 class="section">当前状态</h2><div class="metric small">${label}</div><p>评分 ${t.score}/100。评分代表当前技术条件，不代表一定买入。</p><button class="secondary" data-go="prediction">查看趋势概率</button></div><div class="card"><span class="badge red">📤 减仓 / 重新评估</span><h2 class="section">触发条件</h2>${conditions(['核心投资逻辑失效','利润增长明显转负','价格风险快速上升','达到个人目标'],[false,Number.isFinite(f?.profitGrowth)&&f.profitGrowth<0,s.price>t.high20*.99,false])}</div></div>`;
 $('#stockModule').innerHTML=html;
}
function bar(name,value,color){return `<div class="bar-row"><div class="bar-label"><span>${name}</span><b>${value}</b></div><div class="bar"><span style="width:${value}%;${color?'background:'+color:''}"></span></div></div>`}
function conditions(names,checks){return names.map((x,i)=>`<div class="condition"><input type="checkbox" ${checks[i]?'checked':''} disabled><span>${x}</span></div>`).join('')}
function periodCards(){const t=state.stock.technical;return `<div class="grid g3">${[['⚡ 短期',Math.round((t.score+50)/2),'几天—1个月'],['📈 中期',t.score,'1—6个月'],['💎 长期',Math.round((t.score+65)/2),'6个月以上']].map(x=>`<div class="card"><div class="muted">${x[2]}</div><h2>${x[0]}</h2><div class="metric">${x[1]}</div><span class="badge ${badge(x[1])[0]}">${badge(x[1])[1]}</span></div>`).join('')}</div>`}

function probabilityTone(value){return value>=60?'green':value>=54?'blue':value<=40?'red':value<=46?'orange':'yellow'}
function signed(value){return `${value>=0?'+':''}${fmt(value,1)}%`}
function predictionResult(result){
 const factors=result.horizons[1]?.factors||result.horizons[0]?.factors||{};
 return `<div class="card prediction-hero"><div><p class="eyebrow">${esc(result.symbol)} · 数据截至 ${esc(result.dataThrough)}</p><h2>${esc(result.name)} 趋势概率</h2><p>当前参考价 <b>${fmt(result.currentPrice)}</b> · 对照基准：${esc(result.benchmark)}</p></div><div><span class="badge blue">${result.historyDays} 个交易日数据</span> <span class="badge ${result.market?.regime==='上升环境'?'green':result.market?.regime==='偏弱环境'?'red':'yellow'}">市场：${esc(result.market?.regime||'待判断')}</span></div></div>
 <div class="grid g3 section">${result.horizons.map(item=>`<div class="card horizon-card ${probabilityTone(item.outperformProbability)}"><div class="section-head"><div><span class="muted">未来</span><div class="horizon-days">${item.days}个交易日</div></div><span class="badge ${probabilityTone(item.outperformProbability)}">${item.direction}</span></div><div class="probability"><b>${fmt(item.outperformProbability,1)}%</b><span>跑赢市场基准的历史条件概率</span></div><div class="probability-bar"><span style="width:${item.outperformProbability}%"></span></div><div class="prediction-stats"><div><small>上涨概率</small><b>${fmt(item.positiveProbability,1)}%</b></div><div><small>相似样本中位数</small><b class="${item.expectedReturn>=0?'up':'down'}">${signed(item.expectedReturn)}</b></div><div><small>中间一半范围</small><b>${signed(item.returnLow)} 至 ${signed(item.returnHigh)}</b></div><div><small>可信程度</small><b>${item.confidence}</b></div></div><p class="invalidation"><b>判断失效观察：</b>${esc(item.invalidation)}</p><p class="sample-line">相似样本 ${item.sampleSize} 个 · 历史验证 ${item.validationSamples} 个 · 命中率 ${fmt(item.validationAccuracy,1)}%</p></div>`).join('')}</div>
 <div class="grid g2 section"><div class="card"><h2>当前条件（全部中文）</h2>${[['最近5日平均价格',factors.fiveDayAverage,''],['最近20日平均价格',factors.twentyDayAverage,''],['最近60日平均价格',factors.sixtyDayAverage,''],['20日价格变化',factors.twentyDayMomentum,'%'],['60日价格变化',factors.sixtyDayMomentum,'%'],['相对市场强弱',factors.relativeStrength,'%'],['20日波动程度',factors.twentyDayVolatility,'%'],['近5日/20日成交量比',factors.volumeRatio,'倍']].map(([name,value,unit])=>`<div class="factor-row"><span>${name}</span><b>${fmt(value,unit==='倍'?2:1)}${unit}</b></div>`).join('')}</div><div class="card"><h2>市场环境与方法</h2><div class="factor-row"><span>当前市场状态</span><b>${esc(result.market?.regime||'待判断')}</b></div><div class="factor-row"><span>市场20日价格变化</span><b>${signed(result.market?.twentyDayMomentum)}</b></div><p class="note section">${esc(result.methodology)}</p><p>50%附近表示历史上没有明显方向优势；样本越多、概率离50%越远，参考价值才相对更高。</p><p>命中率只使用历史后30%的验证区间，减少“用同一批数据自我证明”的误差。</p><p class="warning">⚠ 概率不代表保证。重大公告、政策、停牌和市场突变可能让历史规律失效。</p></div></div>`;
}
function predictionHistoryHtml(){return state.predictionHistory.length?`<div class="card section"><h2>我的最近预测记录</h2><div class="table-wrap"><table class="table"><thead><tr><th>时间</th><th>股票</th><th>5日概率</th><th>20日概率</th><th>60日概率</th><th>市场环境</th></tr></thead><tbody>${state.predictionHistory.map(item=>`<tr><td>${new Date(item.createdAt).toLocaleString('zh-CN')}</td><td>${esc(item.name)}<div class="stock-code">${esc(item.symbol)}</div></td>${[5,20,60].map(days=>`<td>${fmt(item.result?.horizons?.find(x=>x.days===days)?.outperformProbability,1)}%</td>`).join('')}<td>${esc(item.result?.market?.regime||'暂无')}</td></tr>`).join('')}</tbody></table></div></div>`:''}
async function predictionPage(){const result=state.prediction;try{state.predictionHistory=(await api('/api/predictions/recent')).predictions||[]}catch{}$('#content').innerHTML=`<div class="card"><div class="section-head"><div><h2>⌁ 趋势预测中心</h2><p class="muted">面向国信金太阳可搜索的沪深 A 股 · 历史条件概率与后段样本验证</p></div><span class="badge blue">无需消耗 AI 余额</span></div><form id="predictionForm" class="prediction-form"><label>股票代码<input id="predictionSymbol" class="input" name="symbol" required maxlength="12" value="${esc(result?.code||'601138')}" placeholder="例如 601138"></label><button class="primary" type="submit">计算趋势概率</button></form><p class="footer-note">输入六位沪深 A 股代码。系统使用真实日线和上证综合指数作比较，不连接国信证券账户，也不能下单。</p></div><div id="predictionResult" class="section">${result?predictionResult(result):'<div class="card empty"><h2>先输入一只股票</h2><p>会同时计算未来5、20、60个交易日三种时间尺度。</p></div>'}</div>${predictionHistoryHtml()}${disclaimer()}`}

async function decisions(){ $('#content').innerHTML=loading();const rows=await quoteMany(state.watch);$('#content').innerHTML=`<div class="grid g3">${[['基本面','25%'],['行业趋势','20%'],['财务质量','15%'],['估值水平','15%'],['技术走势','15%'],['风险因素','10%']].map(x=>`<div class="card"><div class="muted">评分权重</div><div class="metric small">${x[1]}</div><b>${x[0]}</b></div>`).join('')}</div><section class="section"><div class="section-head"><h2>🎯 现在应该怎么办？</h2></div><div class="card">${stockTable(rows)}</div></section>${disclaimer()}` }
async function risks(){ $('#content').innerHTML=loading();const rows=await Promise.all(state.watch.slice(0,10).map(async item=>{const [market,research]=await Promise.allSettled([quote(item.symbol),api('/api/research/'+encodeURIComponent(item.symbol))]);const x=market.status==='fulfilled'?{...item,...market.value}:item,f=research.status==='fulfilled'?research.value.finance:null;const financialRisk=Number.isFinite(f?.profitGrowth)&&f.profitGrowth<0?25:0;return {...x,finance:f,riskScore:clamp(100-(x.technical?.score??50)+financialRisk+(x.price>x.technical?.high20*.97?15:0))}}));rows.sort((a,b)=>b.riskScore-a.riskScore);$('#content').innerHTML=`<div class="card"><div class="section-head"><h2>风险预警中心</h2><span class="badge blue">行情 + 财务联合检查</span></div>${rows.map(x=>`<div class="event"><div class="event-icon">${x.riskScore>=70?'🚨':'⚠'}</div><div><b>${esc(x.name)}</b> <span class="badge ${x.riskScore>=70?'red':x.riskScore>=55?'orange':'green'}">风险提示 ${Math.round(x.riskScore)}</span><p class="muted">技术评分 ${x.technical?.score??'暂无'}；今日变化 ${fmt(x.changePct)}%；利润同比 ${signed(x.finance?.profitGrowth)}。${x.price>x.technical?.high20*.97?'价格接近最近20日高位。':'继续观察关键价格与财务变化。'}</p><button class="link" data-stock="${x.symbol}" data-name="${x.name}">查看完整报告 →</button></div></div>`).join('')||'<div class="empty">股票池为空</div>'}</div>${disclaimer()}` }
async function events(){ $('#content').innerHTML=loading();const researched=await Promise.all(state.watch.slice(0,8).map(async item=>{try{return await api('/api/research/'+encodeURIComponent(item.symbol))}catch{return null}}));const items=researched.filter(Boolean).flatMap(stock=>(stock.announcements||[]).slice(0,3).map(a=>({...a,name:stock.name,symbol:stock.symbol}))).sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,20);$('#content').innerHTML=`<div class="grid g2"><div class="card"><div class="section-head"><h2>股票池最新公告</h2><span class="badge green">自动汇总</span></div>${items.map(a=>`<div class="event"><div class="event-icon">告</div><div><b>${esc(a.name)} · ${esc(a.category)}</b><p>${esc(a.title)}</p><p class="muted">${esc(a.date)}</p><a class="link" href="${a.link}" target="_blank" rel="noopener">查看公告 →</a></div></div>`).join('')||'<div class="empty">股票池暂无可核验公告</div>'}</div><div class="card"><h2>持续追踪清单</h2>${['财务报告与业绩说明会','股东大会和管理层变化','股份回购与股东增减持','重大合同、投资和融资','监管处罚与风险提示'].map(x=>`<div class="condition">□ <span>${x}</span></div>`).join('')}<p class="note section">登录网站时系统会检查股票池行情风险；公告事件会在本页集中显示。</p></div></div>${disclaimer()}` }
async function portfolio(){const rows=await Promise.all(state.portfolio.map(async p=>{try{return {...p,...await quote(p.symbol)}}catch{return p}}));const value=rows.reduce((a,x)=>a+(x.price||x.buy)*x.qty,0),cost=rows.reduce((a,x)=>a+x.buy*x.qty,0);$('#content').innerHTML=`<div class="grid g3"><div class="card"><div class="muted">持仓股票</div><div class="metric">${rows.length}</div></div><div class="card"><div class="muted">当前市值</div><div class="metric">¥${Math.round(value).toLocaleString()}</div></div><div class="card"><div class="muted">浮动收益</div><div class="metric ${value>=cost?'up':'down'}">${cost?fmt((value/cost-1)*100):'0.00'}%</div></div></div><section class="section"><div class="section-head"><h2>持仓明细</h2><button class="primary" data-modal="portfolio">＋ 添加持仓</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>股票</th><th>买入价</th><th>数量</th><th>现价</th><th>收益</th><th>逻辑状态</th><th>操作</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td><b>${x.name}</b><div class="stock-code">${x.symbol}</div></td><td>${fmt(x.buy)}</td><td>${x.qty}</td><td>${fmt(x.price)}</td><td class="${(x.price||x.buy)>=x.buy?'up':'down'}">${fmt(((x.price||x.buy)/x.buy-1)*100)}%</td><td><span class="badge green">核心逻辑待复核</span></td><td><button class="link" data-del-portfolio="${i}">删除</button></td></tr>`).join('')}</tbody></table></div></div></section>${disclaimer()}`}
function theses(){ $('#content').innerHTML=`<div class="section-head"><div><h2>我的投资逻辑档案</h2><p class="muted">保存当初判断，持续与现实对照</p></div><button class="primary" data-modal="thesis">＋ 新建逻辑</button></div><div class="grid g2">${state.theses.map((x,i)=>`<div class="card"><div class="section-head"><div><h2>${x.name}</h2><span class="stock-code">${x.symbol} · ${x.cycle}</span></div><span class="badge green">逻辑待持续验证</span></div><h3>为什么买？</h3><p>${x.reason}</p><h3>失效条件</h3><p class="muted">${x.risk}</p><button class="danger" data-del-thesis="${i}">删除</button></div>`).join('')||'<div class="card empty">还没有投资逻辑</div>'}</div>${disclaimer()}` }
async function brief(){ $('#content').innerHTML=loading();const rows=await quoteMany(state.watch),up=rows.filter(x=>(x.changePct||0)>0).length;$('#content').innerHTML=`<div class="card hero"><p class="eyebrow">DAILY BRIEF · ${new Date().toLocaleDateString('zh-CN')}</p><h2>☀️ 今日 AI 简报</h2><p>股票池 ${rows.length} 只，${up} 只上涨，${rows.length-up} 只下跌或暂无数据。</p></div><div class="grid g2 section"><div class="card"><h2>今天最重要的事情</h2>${rows.sort((a,b)=>Math.abs(b.changePct||0)-Math.abs(a.changePct||0)).slice(0,3).map((x,i)=>`<div class="event"><div class="event-icon">${i+1}</div><div><b>${x.name}</b><p class="muted">今日变化 ${fmt(x.changePct)}%，AI评分 ${x.technical?.score??'暂无'}。</p></div></div>`).join('')}</div><div class="card"><h2>今日原则</h2><p class="note">先核验真实数据，再形成判断；区分好公司和好价格；所有评分都是研究提示，不是收益保证。</p></div></div>${disclaimer()}` }
function settings(){ $('#content').innerHTML=`<div class="grid g2"><div class="card"><h2>当前账户</h2><p><b>${currentUser?.displayName||currentUser?.username}</b></p><p class="muted">${currentUser?.role==='admin'?'管理员':'普通用户'} · 网站不开放注册</p><button id="settingsLogout" class="danger">退出登录</button></div><div class="card"><h2>数据与 AI</h2><div class="condition">✓ <span>真实市场价格与历史行情</span></div><div class="condition">✓ <span>真实公司资料、主要财务指标与公告</span></div><div class="condition">✓ <span>个人股票池、持仓和投资逻辑云端同步</span></div><div class="condition">✓ <span>登录自动风险检查与趋势变化提醒</span></div><div class="condition">${currentUser?'✓':'○'} <span>DeepSeek 中文研究解释</span></div></div></div><p class="footer-note">不同账号的数据分别保存在数据库中；同一账号换设备登录后可以读取自己的股票池、持仓和投资逻辑。</p>` }
async function adminPage(){try{const [{users},{announcements}]=await Promise.all([api('/api/admin/users'),api('/api/admin/announcements')]);$('#content').innerHTML=`<div class="section-head"><div><h2>用户管理</h2><p class="muted">仅管理员可见 · 不开放公开注册</p></div><button class="primary" data-modal="user">＋ 创建用户</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>用户名</th><th>显示名称</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>${users.map(u=>`<tr><td><b>${u.username}</b></td><td>${u.displayName}</td><td>${u.role==='admin'?'管理员':'普通用户'}</td><td><span class="badge ${u.active?'green':'red'}">${u.active?'正常':'已停用'}</span></td><td>${u.role==='admin'?'<span class="muted">主账号</span>':`<button class="link" data-user-toggle="${u.id}">${u.active?'停用':'启用'}</button> · <button class="link" data-user-reset="${u.id}">重置密码</button>`}</td></tr>`).join('')}</tbody></table></div></div><section class="section"><div class="section-head"><div><h2>站内通知</h2><p class="muted">用户进入网站时弹出未读通知</p></div><button class="primary" data-modal="announcement">＋ 发布通知</button></div><div class="grid g2">${announcements.map(a=>`<div class="card"><div class="section-head"><span class="badge ${a.level==='重要'?'red':a.level==='更新'?'blue':'yellow'}">${esc(a.level)}</span><span class="muted">${new Date(a.createdAt).toLocaleDateString('zh-CN')}</span></div><h2>${esc(a.title)}</h2><p>${esc(a.content)}</p><p class="muted">${a.readCount||0} 人已读 · ${a.active?'正在显示':'已停止显示'}</p><button class="${a.active?'danger':'secondary'}" data-announcement-toggle="${a.id}">${a.active?'停止通知':'重新启用'}</button></div>`).join('')||'<div class="card empty">还没有通知</div>'}</div></section>`}catch(e){$('#content').innerHTML=`<div class="card empty">${e.message}</div>`}}
function disclaimer(){return '<p class="footer-note">数据可能延迟，仅用于研究辅助，不构成投资建议。系统不会保证涨跌或收益；缺少来源的数据会明确标记，而不会由 AI 编造。</p>'}
function modal(type){const thesis=type==='thesis';document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><form id="modalForm" class="modal-card"><div class="section-head"><h2>${thesis?'新建投资逻辑':'添加持仓'}</h2><button type="button" class="ghost" data-close>关闭</button></div><div class="form-grid"><label>股票名称<input class="input" name="name" required placeholder="工业富联"></label><label>股票代码<input class="input" name="symbol" required placeholder="601138 或 601138.SS"></label>${thesis?`<label>投资周期<select class="input" name="cycle"><option>短期</option><option>中期</option><option>中长期</option><option>长期</option></select></label><label class="full">为什么买？<textarea name="reason" required></textarea></label><label class="full">逻辑失效条件<textarea name="risk" required></textarea></label>`:`<label>买入价格<input class="input" name="buy" type="number" step="0.01" required></label><label>数量<input class="input" name="qty" type="number" required></label><label>买入日期<input class="input" name="date" type="date" required></label><label class="full">买入逻辑<textarea name="thesis"></textarea></label>`}</div><button class="primary wide">保存</button><input type="hidden" name="type" value="${type}"></form></div>`)}
function userModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><form id="userForm" class="modal-card"><div class="section-head"><h2>创建普通用户</h2><button type="button" class="ghost" data-close>关闭</button></div><div class="form-grid"><label>用户名<input class="input" name="username" required minlength="3" placeholder="至少3位，例如 test01"></label><label>显示名称<input class="input" name="displayName" required placeholder="例如 张三"></label><label class="full">初始密码<input class="input" name="password" type="password" required minlength="6" placeholder="至少6位"></label></div><button class="primary wide" type="submit">创建账号</button></form></div>`)}
function announcementAdminModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><form id="announcementForm" class="modal-card"><div class="section-head"><h2>发布站内通知</h2><button type="button" class="ghost" data-close>关闭</button></div><div class="form-grid"><label>通知类型<select class="input" name="level"><option>通知</option><option selected>更新</option><option>重要</option></select></label><label class="full">标题<input class="input" name="title" required maxlength="120" placeholder="例如：智能选股功能已更新"></label><label class="full">通知内容<textarea name="content" required maxlength="2000" placeholder="写清楚这次更新或需要用户注意的事情"></textarea></label></div><button class="primary wide" type="submit">立即发布</button></form></div>`)}
function showAnnouncementQueue(items){if(!items?.length||$('#announcementPopup'))return;const a=items[0];document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="announcementPopup"><div class="modal-card announcement-card"><div class="announcement-icon">🔔</div><span class="badge ${a.level==='重要'?'red':a.level==='更新'?'blue':'yellow'}">${esc(a.level)}</span><h2>${esc(a.title)}</h2><p>${esc(a.content)}</p><p class="muted">${new Date(a.createdAt).toLocaleDateString('zh-CN')}</p><div class="announcement-actions"><button class="ghost" data-announcement-later>稍后提醒</button><button class="primary" data-announcement-read="${a.id}">我知道了</button></div></div></div>`);$('#announcementPopup').dataset.remaining=JSON.stringify(items.slice(1))}
async function showUnreadAnnouncements(){try{const {announcements}=await api('/api/announcements');showAnnouncementQueue(announcements)}catch{}}
function showAlertQueue(items){if(!items?.length)return;if($('#announcementPopup')||$('#alertPopup')){setTimeout(()=>showAlertQueue(items),1200);return}const a=items[0];document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="alertPopup"><div class="modal-card announcement-card"><div class="announcement-icon">${a.level==='风险'?'🚨':'🔔'}</div><span class="badge ${a.level==='风险'?'red':'orange'}">${esc(a.level)}</span><h2>${esc(a.title)}</h2><p>${esc(a.content)}</p><p class="muted">${new Date(a.createdAt).toLocaleString('zh-CN')}</p><div class="announcement-actions"><button class="ghost" data-alert-later>稍后提醒</button><button class="primary" data-alert-read="${a.id}">我知道了</button></div></div></div>`);$('#alertPopup').dataset.remaining=JSON.stringify(items.slice(1))}
async function monitorAndShowAlerts(){await api('/api/monitor',{method:'POST'}).catch(()=>{});try{const {alerts}=await api('/api/alerts');showAlertQueue(alerts)}catch{}}

async function render(){if(state.page==='stock')return renderStock();const routes={dashboard,watchlist,search:searchPage,aiChat:aiChatPage,aiScreen:aiScreenPage,prediction:predictionPage,decisions,risks,events,portfolio,theses,brief,settings,admin:adminPage};await routes[state.page]?.()}
document.addEventListener('click',async e=>{
 const page=e.target.closest('[data-page]')?.dataset.page||e.target.closest('[data-go]')?.dataset.go;if(page)return go(page);
 const stock=e.target.closest('[data-stock]');if(stock)return openStock(stock.dataset.stock,stock.dataset.name);
 const tab=e.target.closest('[data-tab]');if(tab){state.tab=tab.dataset.tab;renderStock();return}
 const add=e.target.closest('[data-add]');if(add){if(!state.watch.some(x=>x.symbol===add.dataset.add)){state.watch.push({symbol:add.dataset.add,code:add.dataset.add,name:add.dataset.name});store.set('watch',state.watch);toast('已加入股票池')}return}
 const rem=e.target.closest('[data-remove]');if(rem){state.watch=state.watch.filter(x=>x.symbol!==rem.dataset.remove);store.set('watch',state.watch);watchlist();return}
 if(e.target.closest('[data-modal]')){const type=e.target.closest('[data-modal]').dataset.modal;return type==='user'?userModal():type==='announcement'?announcementAdminModal():modal(type)}
 if(e.target.closest('[data-close]')||e.target.classList.contains('modal'))return $('#modal')?.remove();
 if(e.target.closest('[data-clear-chat]')){state.aiMessages=[];store.set('aiMessages',[]);aiChatPage();return}
 const ar=e.target.closest('[data-announcement-read]');if(ar){const popup=$('#announcementPopup'),remaining=JSON.parse(popup?.dataset.remaining||'[]');await api('/api/announcements/'+ar.dataset.announcementRead+'/read',{method:'POST'});popup?.remove();showAnnouncementQueue(remaining);return}
 if(e.target.closest('[data-announcement-later]')){$('#announcementPopup')?.remove();return}
 const alertRead=e.target.closest('[data-alert-read]');if(alertRead){const popup=$('#alertPopup'),remaining=JSON.parse(popup?.dataset.remaining||'[]');await api('/api/alerts/'+alertRead.dataset.alertRead+'/read',{method:'POST'});popup?.remove();showAlertQueue(remaining);return}
 if(e.target.closest('[data-alert-later]')){$('#alertPopup')?.remove();return}
 const at=e.target.closest('[data-announcement-toggle]');if(at){await api('/api/admin/announcements/'+at.dataset.announcementToggle,{method:'PATCH',body:JSON.stringify({action:'toggle'})});toast('通知状态已更新');adminPage();return}
 const suggestion=e.target.closest('[data-ai-question]');if(suggestion){const input=document.querySelector('#aiChatForm textarea');if(input){input.value=suggestion.dataset.aiQuestion;input.focus()}return}
 const dp=e.target.closest('[data-del-portfolio]');if(dp){state.portfolio.splice(+dp.dataset.delPortfolio,1);store.set('portfolio',state.portfolio);portfolio();return}
 const dt=e.target.closest('[data-del-thesis]');if(dt){state.theses.splice(+dt.dataset.delThesis,1);store.set('theses',state.theses);theses();return}
 const ut=e.target.closest('[data-user-toggle]');if(ut){await api('/api/admin/users/'+ut.dataset.userToggle,{method:'PATCH',body:JSON.stringify({action:'toggle'})});toast('用户状态已更新');adminPage();return}
 const ur=e.target.closest('[data-user-reset]');if(ur){const password=prompt('请输入至少6位的新密码');if(password){await api('/api/admin/users/'+ur.dataset.userReset,{method:'PATCH',body:JSON.stringify({action:'reset',password})});toast('密码已重置')}return}
 if(e.target.id==='settingsLogout')return logout();
});
document.addEventListener('submit',async e=>{
 e.preventDefault();
 if(e.target.id==='loginForm'){try{const result=await api('/api/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});currentUser=result.user;loadUserState();await loadCloudState();$('#login').classList.add('hidden');$('#shell').classList.remove('hidden');go('dashboard');showUnreadAnnouncements();monitorAndShowAlerts()}catch(err){$('#loginError').textContent=err.message}return}
 if(e.target.id==='searchForm')return doSearch($('#searchInput').value.trim());
 if(e.target.id==='aiChatForm'){const button=e.target.querySelector('button[type="submit"]'),d=Object.fromEntries(new FormData(e.target)),history=state.aiMessages.slice(-6);state.aiMessages.push({role:'user',content:d.question});store.set('aiMessages',state.aiMessages);button.disabled=true;button.textContent='AI 分析中…';try{const result=await api('/api/ai/chat',{method:'POST',body:JSON.stringify({symbol:d.symbol,question:d.question,history})});state.aiMessages.push({role:'assistant',content:result.answer});store.set('aiMessages',state.aiMessages);await aiChatPage()}catch(err){state.aiMessages.push({role:'assistant',content:'暂时无法回答：'+err.message});store.set('aiMessages',state.aiMessages);await aiChatPage()}return}
 if(e.target.id==='aiScreenForm'){const box=$('#screenResult'),button=e.target.querySelector('button[type="submit"]'),d=Object.fromEntries(new FormData(e.target));state.aiScreenCriteria=d;store.set('aiScreenCriteria',d);button.disabled=true;button.textContent='正在扫描扩大样本并筛选…';box.innerHTML=loading();try{state.aiScreen=await api('/api/ai/screen',{method:'POST',body:JSON.stringify(d)});await aiScreenPage()}catch(err){box.innerHTML=`<div class="card empty"><h2>暂时无法完成筛选</h2><p>${esc(err.message)}</p></div>`;button.disabled=false;button.textContent='重新筛选'}return}
 if(e.target.id==='predictionForm'){const box=$('#predictionResult'),button=e.target.querySelector('button[type="submit"]'),d=Object.fromEntries(new FormData(e.target));button.disabled=true;button.textContent='正在读取两年行情并验证…';box.innerHTML=loading();try{state.prediction=await api('/api/prediction',{method:'POST',body:JSON.stringify(d)});predictionPage()}catch(err){box.innerHTML=`<div class="card empty"><h2>暂时无法完成趋势计算</h2><p>${esc(err.message)}</p><p>请确认是有效的六位沪深 A 股代码，或稍后再试。</p></div>`;button.disabled=false;button.textContent='重新计算'}return}
 if(e.target.id==='modalForm'){const d=Object.fromEntries(new FormData(e.target));if(d.type==='portfolio'){state.portfolio.push({symbol:d.symbol.toUpperCase(),name:d.name,buy:+d.buy,qty:+d.qty,date:d.date,thesis:d.thesis});store.set('portfolio',state.portfolio);$('#modal').remove();portfolio()}else{state.theses.push({symbol:d.symbol.toUpperCase(),name:d.name,cycle:d.cycle,created:new Date().toISOString().slice(0,10),reason:d.reason,risk:d.risk});store.set('theses',state.theses);$('#modal').remove();theses()}toast('已保存')}
 if(e.target.id==='userForm'){const d=Object.fromEntries(new FormData(e.target));try{await api('/api/admin/users',{method:'POST',body:JSON.stringify(d)});$('#modal').remove();toast('普通用户已创建');adminPage()}catch(err){toast(err.message)}}
 if(e.target.id==='announcementForm'){const d=Object.fromEntries(new FormData(e.target));try{await api('/api/admin/announcements',{method:'POST',body:JSON.stringify(d)});$('#modal').remove();toast('通知已发布');adminPage()}catch(err){toast(err.message)}}
});
async function logout(){await api('/api/logout',{method:'POST'}).catch(()=>{});location.reload()}
$('#logoutBtn').onclick=logout;$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
setInterval(()=>$('#clock').textContent=new Date().toLocaleString('zh-CN',{hour:'2-digit',minute:'2-digit',month:'short',day:'numeric'}),1000);
(async()=>{try{const s=await api('/api/session');if(s.authenticated){currentUser=s.user;loadUserState();await loadCloudState();$('#login').classList.add('hidden');$('#shell').classList.remove('hidden');navRender();render();showUnreadAnnouncements();monitorAndShowAlerts()}}catch{}})();
